---
driver_plugin: vagrant
driver_config:
    require_chef_omnibus: 12

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.6

suites:
  - name: source
    run_list:
      - recipe[exabgp::source]
    attributes:
      exabgp:
        source_version: '3.4'
        hubot:
          enable: true
